// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SpindleSoft.Views
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MeasurementReport : MeasurementReportBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            this.Write(@"
<html>
	<head>
		<style>
			table {
				font-family: arial, sans-serif;
				border-collapse: collapse;
				width: 45%;
				margin: 5px;
			}

			td, th {
				border: 1px solid #dddddd;
				text-align: left;
				padding: 8px;
				width: 50%
			}
			
		</style>
	</head>
	<body onload=""PrintMeasurement()""> 
	<h2>Measurements</h2> 
	<hr/>
	<table style=""float:right; margin-top:0px"">
			<tr>
				<th colspan=""2"">Customer Profile</th>
			</tr>			
			<tr>
				<td>Order No.</td>  						
				");
            
            #line 37 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 37 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.ID));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 37 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Customer Name </td>  \r\n\t\t\t\t");
            
            #line 41 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 41 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._cust.Name));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 41 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr> \r\n\t\t\t<tr> \r\n\t\t\t\t<td>Order Name </td>  \r\n\t\t\t\t");
            
            #line 45 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 45 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Name));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 45 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Quantity</td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 49 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 49 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Quantity));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 49 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\t\t\t\t\r\n\t\t</table> \r\n\t<div class=\"MeasureTable\">\r\n\t\r\n\t\t<table>\r\n\t\t\t<tr>\r\n\t\t" +
                    "\t\t<th colspan=\"2\">Basic Measurement</th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Length </td" +
                    ">  \r\n\t\t\t\t");
            
            #line 60 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 60 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Length));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 60 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr> \r\n\t\t\t<tr> \r\n\t\t\t\t<td>Waist </td>  \r\n\t\t\t\t");
            
            #line 64 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 64 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Waist));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 64 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Chest </td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 68 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 68 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Chest));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 68 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Hip </td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 72 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 72 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Hip));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 72 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Front </td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 76 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 76 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Front));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 76 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Back </td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 80 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 80 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Back));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 80 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</table>   \t\t\r\n\t\t<table>\r\n\t\t\t<tr>\r\n\t\t\t\t<th colspan=\"2\">Sleeve Measure" +
                    "ment</th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>ArmHole </td>  \r\n\t\t\t\t");
            
            #line 89 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 89 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.SleeveArmHole));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 89 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr> \r\n\t\t\t<tr> \r\n\t\t\t\t<td>Length </td>  \r\n\t\t\t\t");
            
            #line 93 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 93 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.SleeveLength));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 93 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Loose </td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 97 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 97 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.SleeveLoose));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 97 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</table>   \t\t\r\n\t\t<table>\r\n\t\t\t<tr>\r\n\t\t\t\t<th colspan=\"2\">Shoulder Measu" +
                    "rement</th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Shoulder </td>  \r\n\t\t\t\t");
            
            #line 106 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 106 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Shoulder));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 106 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr> \r\n\t\t\t<tr> \r\n\t\t\t\t<td>D </td>  \r\n\t\t\t\t");
            
            #line 110 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 110 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.D));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 110 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</table>\r\n\t\t<table>\r\n\t\t\t<tr>\r\n\t\t\t\t<th colspan=\"2\">Bottom Measurement<" +
                    "/th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Hip</td>  \r\n\t\t\t\t");
            
            #line 119 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 119 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.BottomHip));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 119 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr> \r\n\t\t\t<tr> \r\n\t\t\t\t<td>Waist</td>  \r\n\t\t\t\t");
            
            #line 123 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 123 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.BottomWaist));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 123 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Length</td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 127 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 127 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.BottomLength));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 127 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Loose</td>  \t\t\t\t\t\t\r\n\t\t\t\t");
            
            #line 131 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 131 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.BottomLoose));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 131 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</table>\t\r\n\t\t\r\n\t\t<table style=\"width:100%\">\r\n\t\t\t<tr>\r\n\t\t\t\t<th colspan" +
                    "=\"2\">Comments</th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t");
            
            #line 140 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 { 
            
            #line default
            #line hidden
            this.Write(" <td>");
            
            #line 140 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this._orderItem.Comment));
            
            #line default
            #line hidden
            this.Write(" </td>");
            
            #line 140 "C:\Users\NSuhanShetty\Documents\Visual Studio 2013\Projects\SpindleSoft\SpindleSoft\Views\MeasurementReport.tt"
 }  
            
            #line default
            #line hidden
            this.Write(@"			</tr> 			
		</table>	
	</div>
	</body>
<script>
		function PrintMeasurement() {
			window.onfocus = function () { setTimeout(function () { window.close(); }, 500); }
		}
		setTimeout(function () { window.print(); }, 500);       
</script>
</html>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class MeasurementReportBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
